/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import DAO.UsuarioDAO;
import javax.swing.JOptionPane;
import java.sql.*;
import UtilSQL.ConexaoSQL;

/**
 *
 * @author ester
 */
public class AlterarSenhaView extends javax.swing.JFrame {

    /**
     * Creates new form AlterarSenhaView
     */
    public AlterarSenhaView() {
        initComponents();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        novaTitulo = new javax.swing.JPanel();
        AlterarTitulo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        emailTitulo = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        txtNovaSenha = new javax.swing.JTextField();
        bttNovaSenha = new javax.swing.JButton();
        bttExcluirUsuario = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        bttLogin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        novaTitulo.setBackground(new java.awt.Color(51, 255, 153));
        novaTitulo.setPreferredSize(new java.awt.Dimension(643, 368));

        AlterarTitulo.setFont(new java.awt.Font("Lucida Console", 1, 24)); // NOI18N
        AlterarTitulo.setForeground(new java.awt.Color(0, 0, 0));
        AlterarTitulo.setText("ALTERAR SENHA");

        jLabel2.setFont(new java.awt.Font("Lucida Console", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Nova Senha:");

        emailTitulo.setFont(new java.awt.Font("Lucida Console", 1, 12)); // NOI18N
        emailTitulo.setForeground(new java.awt.Color(0, 0, 0));
        emailTitulo.setText("E-mail:");

        txtEmail.setBackground(new java.awt.Color(153, 153, 153));

        txtNovaSenha.setBackground(new java.awt.Color(153, 153, 153));

        bttNovaSenha.setBackground(new java.awt.Color(255, 255, 255));
        bttNovaSenha.setForeground(new java.awt.Color(0, 0, 0));
        bttNovaSenha.setText("Nova Senha");
        bttNovaSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttNovaSenhaActionPerformed(evt);
            }
        });

        bttExcluirUsuario.setBackground(new java.awt.Color(255, 255, 255));
        bttExcluirUsuario.setForeground(new java.awt.Color(0, 0, 0));
        bttExcluirUsuario.setText("Excluir Usuario");
        bttExcluirUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttExcluirUsuarioActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Lucida Console", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Desja excluir o seu cadastro?");

        bttLogin.setBackground(new java.awt.Color(255, 255, 255));
        bttLogin.setForeground(new java.awt.Color(0, 0, 0));
        bttLogin.setText("LOGIN");
        bttLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout novaTituloLayout = new javax.swing.GroupLayout(novaTitulo);
        novaTitulo.setLayout(novaTituloLayout);
        novaTituloLayout.setHorizontalGroup(
            novaTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, novaTituloLayout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addGroup(novaTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, novaTituloLayout.createSequentialGroup()
                        .addGap(0, 129, Short.MAX_VALUE)
                        .addComponent(AlterarTitulo)
                        .addGap(202, 202, 202))
                    .addGroup(novaTituloLayout.createSequentialGroup()
                        .addGroup(novaTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(novaTituloLayout.createSequentialGroup()
                                .addComponent(emailTitulo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(novaTituloLayout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtNovaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, novaTituloLayout.createSequentialGroup()
                                .addGap(115, 115, 115)
                                .addComponent(jLabel3)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, novaTituloLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(novaTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, novaTituloLayout.createSequentialGroup()
                        .addComponent(bttLogin)
                        .addGap(275, 275, 275))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, novaTituloLayout.createSequentialGroup()
                        .addComponent(bttNovaSenha)
                        .addGap(263, 263, 263))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, novaTituloLayout.createSequentialGroup()
                        .addComponent(bttExcluirUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(251, 251, 251))))
        );
        novaTituloLayout.setVerticalGroup(
            novaTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(novaTituloLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(AlterarTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addGroup(novaTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailTitulo)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(novaTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNovaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(bttNovaSenha)
                .addGap(24, 24, 24)
                .addComponent(bttLogin)
                .addGap(26, 26, 26)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bttExcluirUsuario)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(novaTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addComponent(novaTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bttExcluirUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttExcluirUsuarioActionPerformed
        // TODO add your handling code here:
        dispose();
        new ExcluirUsuarioView().setVisible(true);
    }//GEN-LAST:event_bttExcluirUsuarioActionPerformed

    private void bttNovaSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttNovaSenhaActionPerformed
        // TODO add your handling code here:
        String email = txtEmail.getText().trim();
        String senhaNova = txtNovaSenha.getText().trim();

        if (email.isEmpty() || senhaNova.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preencha todos os campos!!");
            return;
        }
        try {
            Connection conexao = ConexaoSQL.conectar();
            UsuarioDAO dao = new UsuarioDAO(conexao);
            boolean sucesso = dao.alterarSenha(email, senhaNova);
            conexao.close();
            if (sucesso) {

                JOptionPane.showMessageDialog(null, "SENHA ALTERADA COM SUCESSO!!");
                dispose();
                new LoginView().setVisible(true);
            } else {
                JOptionPane.showMessageDialog(null, "FALHA AO ALTERAR SENHA.E-MAIL NÃO ENCONTRADO! ");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "ERRO: " + e.getMessage());
            e.printStackTrace();

        }
    }//GEN-LAST:event_bttNovaSenhaActionPerformed

    private void bttLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttLoginActionPerformed
        // TODO add your handling code here:
        dispose();
        new LoginView().setVisible(true);
    }//GEN-LAST:event_bttLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlterarSenhaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlterarSenhaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlterarSenhaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlterarSenhaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AlterarSenhaView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AlterarTitulo;
    private javax.swing.JButton bttExcluirUsuario;
    private javax.swing.JButton bttLogin;
    private javax.swing.JButton bttNovaSenha;
    private javax.swing.JLabel emailTitulo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel novaTitulo;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNovaSenha;
    // End of variables declaration//GEN-END:variables
}
