/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import DAO.MusicaDAO;
import DAO.HistoricoDAO;
import DAO.UsuarioDAO;
import Model.Artista;
import Model.Genero;
import Model.Historico;
import Model.Musica;
import Model.Usuario;
import UtilSQL.ConexaoSQL;
import java.util.List;
import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.*;
import java.util.ArrayList;

/**
 *
 * @author ester
 */
public class HistoricoView extends javax.swing.JFrame {

    /**
     * Creates new form HistoricoView
     */
    private Usuario usuario;
    private MusicaDAO musicaDAO;
    private DAO.HistoricoDAO historicoDAO;
    private JPanel painelResultados;

    public HistoricoView(Usuario usuario) {
        this.usuario = usuario;

        try {
            Connection conexao = ConexaoSQL.conectar();
            this.musicaDAO = new MusicaDAO(conexao);
            this.historicoDAO = new DAO.HistoricoDAO(conexao);

        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Erro ao conectar com o banco.");
            return;
        }

        initComponents();
        configurarPainelResultados();
    }

    private void configurarPainelResultados() {
        painelResultados = new JPanel();
        painelResultados.setLayout(new BoxLayout(painelResultados, BoxLayout.Y_AXIS));
        painelResultados.setBackground(new Color(50, 255, 153));

        JScrollPane scrollPane = new JScrollPane(painelResultados);
        scrollPane.setPreferredSize(new Dimension(300, 300));

        painelResultadosContainer.setLayout(new BorderLayout());
        painelResultadosContainer.add(scrollPane, BorderLayout.CENTER);
        painelResultadosContainer.revalidate();
        painelResultadosContainer.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        comboBoxVisualizar = new javax.swing.JComboBox<>();
        bttVisualizar = new javax.swing.JButton();
        painelResultadosContainer = new javax.swing.JPanel();
        bttVoltar = new javax.swing.JButton();

        jMenuBar1.setBackground(new java.awt.Color(50, 255, 153));

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(50, 255, 153));

        comboBoxVisualizar.setBackground(new java.awt.Color(255, 255, 255));
        comboBoxVisualizar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Últimas 10 musicas buscadas", "Músicas curtidas", "Músicas descurtidas" }));
        comboBoxVisualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxVisualizarActionPerformed(evt);
            }
        });

        bttVisualizar.setBackground(new java.awt.Color(255, 255, 255));
        bttVisualizar.setForeground(new java.awt.Color(0, 0, 0));
        bttVisualizar.setText("Visualizar");
        bttVisualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttVisualizarActionPerformed(evt);
            }
        });

        painelResultadosContainer.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout painelResultadosContainerLayout = new javax.swing.GroupLayout(painelResultadosContainer);
        painelResultadosContainer.setLayout(painelResultadosContainerLayout);
        painelResultadosContainerLayout.setHorizontalGroup(
            painelResultadosContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 421, Short.MAX_VALUE)
        );
        painelResultadosContainerLayout.setVerticalGroup(
            painelResultadosContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 228, Short.MAX_VALUE)
        );

        bttVoltar.setBackground(new java.awt.Color(255, 255, 255));
        bttVoltar.setForeground(new java.awt.Color(0, 0, 0));
        bttVoltar.setText("Voltar");
        bttVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(comboBoxVisualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bttVisualizar)
                        .addGap(58, 58, 58))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(painelResultadosContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bttVoltar)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bttVisualizar)
                    .addComponent(comboBoxVisualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(painelResultadosContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(bttVoltar)))
                .addContainerGap(70, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboBoxVisualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxVisualizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxVisualizarActionPerformed

    private void bttVisualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttVisualizarActionPerformed
        // TODO add your handling code here:
        String opcao = (String) comboBoxVisualizar.getSelectedItem();
        painelResultados.removeAll();

        try {
            List<Musica> musicas;

            switch (opcao) {
                case "Últimas 10 musicas buscadas":
                    musicas = historicoDAO.buscarUltimos10(usuario.getId());
                    break;
                case "Músicas curtidas":
                    musicas = musicaDAO.buscarCurtidas(usuario.getId());
                    break;
                case "Músicas descurtidas":
                    musicas = musicaDAO.buscarDescurtidas(usuario.getId());
                    break;
                default:
                    musicas = new ArrayList<>();
            }
            if (musicas.isEmpty()) {
                painelResultados.add(new JLabel("Nenhuma música encontrada."));
            } else {
                for (Musica m : musicas) {
                    JPanel musicaPanel = new JPanel(new BorderLayout());
                    musicaPanel.setBorder(BorderFactory.createLineBorder(Color.BLACK));
                    musicaPanel.setMaximumSize(new Dimension(680, 60));
                    musicaPanel.setBackground(Color.WHITE);

                    String texto = "<html><b>" + m.getNome() + "</b> - "
                            + m.getArtista().getNome() + " (" + m.getGenero().getNome() + ")</html>";

                    JLabel lblInfo = new JLabel(texto);
                    lblInfo.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));
                    musicaPanel.add(lblInfo, BorderLayout.CENTER);

                    painelResultados.add(musicaPanel);
                }
            }

            painelResultados.revalidate();
            painelResultados.repaint();

        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Erro ao carregar histórico.");
        }


    }//GEN-LAST:event_bttVisualizarActionPerformed

    private void bttVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttVoltarActionPerformed
        // TODO add your handling code here:
        dispose();
        TelaInicialView tela = new TelaInicialView(usuario);
        tela.setVisible(true);
    }//GEN-LAST:event_bttVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HistoricoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HistoricoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HistoricoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HistoricoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        try {
            Connection conexao = ConexaoSQL.conectar();
            UsuarioDAO usuarioDAO = new UsuarioDAO(conexao);
            Usuario usuario = usuarioDAO.buscarUsuarioPorId(1);

            if (usuario != null) {
                java.awt.EventQueue.invokeLater(() -> {
                    new HistoricoView(usuario).setVisible(true);
                });
            } else {
                System.out.println("Usuário não encontrado no banco.");
            }
        } catch (Exception e) {
            e.printStackTrace();
        };
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttVisualizar;
    private javax.swing.JButton bttVoltar;
    private javax.swing.JComboBox<String> comboBoxVisualizar;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel painelResultadosContainer;
    // End of variables declaration//GEN-END:variables
}
